apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -hml

namespace: flask-hml

resources:
- route.yaml
- hpa.yaml
- ns.yaml
- rq-flask.yaml
- ../../base
- rolebinding.yaml
- sa.yaml
- obc.yaml

images:
- name: flaskimage
  newName: quay.io/lagomes/flask-s3-upload
  newTag: v3
labels:
- includeSelectors: true
  pairs:
    env: flaskupload

patches:
- path: patch-deployment.yaml
