apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flask-sa-anyuid
subjects:
  - kind: ServiceAccount
    name: flask-sa-hml
    namespace: flask-hml
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
