# https://access.redhat.com/documentation/en-us/openshift_container_platform/4.10/html/building_applications/quotas#quotas-sample-resource-quota-definitions_quotas-setting-per-project

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-flask
spec:
  hard:
    pods: "5"
    requests.cpu: "300m"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "4Gi"

