---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask
spec:
  type: ClusterIP
  selector:
    app: flask  
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP