---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-anyuid-rolebinding
  namespace: minio-ocp
subjects:
  - kind: ServiceAccount
    name: minio-sa
    namespace: minio-ocp
roleRef:
  kind: Role
  name: minio-anyuid-role
  apiGroup: rbac.authorization.k8s.io
