apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  labels:
    app: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-container
          envFrom:
            - secretRef:
                name: flask-secret
          resources:
            requests:
              memory: "16Mi"
              cpu: 10m
            limits:
              memory: "128Mi"
              cpu: 500m
          image: flaskimage
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
