apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-ocp

labels:
- includeSelectors: true
  pairs:
    app: minio

resources:
  - deployment.yml
  - role.yml
  - routes.yml

images:
- name: minioimage
  newName: quay.io/minio/minio
  newTag: latest

